# Generated by Django 2.2.7 on 2019-11-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='userId',
        ),
        migrations.AddField(
            model_name='board',
            name='user',
            field=models.CharField(default='1', max_length=500),
        ),
    ]
