# Generated by Django 2.2.7 on 2019-11-19 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0003_board_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='user',
        ),
    ]
