# Generated by Django 2.2.7 on 2019-12-09 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0005_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='note',
            new_name='content',
        ),
    ]
