# Generated by Django 2.2.7 on 2019-12-09 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0006_auto_20191209_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='x',
            field=models.CharField(default='0', max_length=500),
        ),
        migrations.AddField(
            model_name='note',
            name='y',
            field=models.CharField(default='0', max_length=500),
        ),
    ]
